// Style direction: Civic Observatory — category choice as a calm, high-signal control room.
import { useMemo, useState } from 'react'
import { getLanguage } from '../data/languages'
import './CategoryPage.css'

const categoryData = [
  { id: 'education', code: 'ED', title: 'Education', sub: 'Scholarships & learning', description: 'Find scholarships, fee support, fellowships, and education access programmes.', current: '43 local records', national: 'DBT directory includes education schemes', tone: 'amber' },
  { id: 'health', code: 'HL', title: 'Health & wellness', sub: 'Care, insurance & treatment', description: 'Explore health cover, treatment support, maternal care, and wellness assistance.', current: 'National directory', national: 'PM-JAY and health missions', tone: 'blue' },
  { id: 'jobs', code: 'JS', title: 'Jobs & skills', sub: 'Training & employment', description: 'Move toward skills, apprenticeships, job placement, and livelihood training.', current: 'National directory', national: 'Skill India and apprenticeship routes', tone: 'teal' },
  { id: 'housing', code: 'HU', title: 'Housing & utilities', sub: 'Homes, water & energy', description: 'Find support for housing, sanitation, electricity, cooking fuel, and water.', current: 'National directory', national: 'Housing and utility programmes', tone: 'violet' },
  { id: 'finance', code: 'FI', title: 'Finance & insurance', sub: 'Accounts, credit & cover', description: 'Compare financial inclusion, pension, insurance, credit, and income-support routes.', current: 'National directory', national: 'DBT and financial-service schemes', tone: 'amber' },
  { id: 'agriculture', code: 'AL', title: 'Agriculture & livelihoods', sub: 'Farms, livestock & rural work', description: 'Find farmer income support, crop insurance, equipment, and rural enterprise help.', current: 'National directory', national: 'PM-KISAN and agriculture schemes', tone: 'green' },
  { id: 'women', code: 'WC', title: 'Women & child', sub: 'Safety, care & opportunity', description: 'Discover support for women, children, nutrition, protection, and family wellbeing.', current: 'National directory', national: 'Women and child development routes', tone: 'rose' },
  { id: 'social', code: 'SJ', title: 'Social justice', sub: 'Inclusion & dignity', description: 'Find welfare and inclusion programmes for disadvantaged and historically underserved communities.', current: 'National directory', national: 'Social justice ministry schemes', tone: 'orange' },
  { id: 'disability', code: 'DS', title: 'Disability support', sub: 'Access, aids & inclusion', description: 'Locate scholarships, assistive devices, rehabilitation, and accessibility support.', current: 'National directory', national: 'DEPwD support programmes', tone: 'cyan' },
]

const labels = {
  English: { back: 'SchemeSetu', eyebrow: 'STEP 01 / CHOOSE YOUR SIGNAL', title: 'What kind of support\nare you looking for?', body: 'Start with the part of life where you need a clearer path. Your next questions will adapt to this choice.', search: 'Search a category', searchHint: 'Try “education”, “farmer”, or “health”', signal: 'SELECT ONE TO CONTINUE', foot: 'Nine routes · one focused next step' },
  Hindi: { back: 'स्कीम सेतु', eyebrow: 'चरण 01 / सहायता चुनें', title: 'आप किस तरह की\nसहायता ढूँढ रहे हैं?', body: 'अपने जीवन के उस हिस्से से शुरुआत करें जहाँ आपको स्पष्ट रास्ता चाहिए। अगले सवाल इसी चुनाव के अनुसार बदलेंगे।', search: 'श्रेणी खोजें', searchHint: '“शिक्षा”, “किसान” या “स्वास्थ्य” आज़माएँ', signal: 'जारी रखने के लिए एक चुनें', foot: 'नौ रास्ते · एक स्पष्ट अगला कदम' },
  Marathi: { back: 'योजना सेतू', eyebrow: 'चरण 01 / मदत निवडा', title: 'तुम्ही कोणत्या प्रकारची\nमदत शोधत आहात?', body: 'जिथे तुम्हाला स्पष्ट मार्ग हवा आहे त्या जीवनाच्या भागापासून सुरुवात करा. पुढील प्रश्न तुमच्या निवडीप्रमाणे बदलतील.', search: 'श्रेणी शोधा', searchHint: '“शिक्षण”, “शेतकरी” किंवा “आरोग्य” वापरून पाहा', signal: 'पुढे जाण्यासाठी एक निवडा', foot: 'नऊ मार्ग · एक स्पष्ट पुढील पाऊल' },
  Tamil: { back: 'ஸ்கீம் சேது', eyebrow: 'படி 01 / ஆதரவைத் தேர்ந்தெடுக்கவும்', title: 'நீங்கள் எந்த வகையான\nஆதரவைத் தேடுகிறீர்கள்?', body: 'தெளிவான பாதை தேவைப்படும் வாழ்க்கைப் பகுதியிலிருந்து தொடங்குங்கள். அடுத்த கேள்விகள் உங்கள் தேர்வுக்கு ஏற்ப மாறும்.', search: 'வகையைத் தேடுங்கள்', searchHint: '“கல்வி”, “விவசாயி” அல்லது “சுகாதாரம்” முயற்சிக்கவும்', signal: 'தொடர ஒன்றைத் தேர்ந்தெடுக்கவும்', foot: 'ஒன்பது பாதைகள் · ஒரு தெளிவான அடுத்த படி' },
  Kannada: { back: 'ಸ್ಕೀಮ್ ಸೇತು', eyebrow: 'ಹಂತ 01 / ಬೆಂಬಲ ಆಯ್ಕೆಮಾಡಿ', title: 'ನೀವು ಯಾವ ರೀತಿಯ\nಬೆಂಬಲವನ್ನು ಹುಡುಕುತ್ತಿದ್ದೀರಿ?', body: 'ನಿಮಗೆ ಸ್ಪಷ್ಟ ದಾರಿ ಬೇಕಿರುವ ಜೀವನದ ಭಾಗದಿಂದ ಪ್ರಾರಂಭಿಸಿ. ಮುಂದಿನ ಪ್ರಶ್ನೆಗಳು ನಿಮ್ಮ ಆಯ್ಕೆಗೆ ಅನುಗುಣವಾಗಿ ಬದಲಾಗುತ್ತವೆ.', search: 'ವರ್ಗವನ್ನು ಹುಡುಕಿ', searchHint: '“ಶಿಕ್ಷಣ”, “ರೈತ” ಅಥವಾ “ಆರೋಗ್ಯ” ಪ್ರಯತ್ನಿಸಿ', signal: 'ಮುಂದುವರಿಸಲು ಒಂದನ್ನು ಆಯ್ಕೆಮಾಡಿ', foot: 'ಒಂಬತ್ತು ದಾರಿಗಳು · ಒಂದು ಸ್ಪಷ್ಟ ಮುಂದಿನ ಹೆಜ್ಜೆ' },
  Malayalam: { back: 'സ്കീം സേതു', eyebrow: 'ഘട്ടം 01 / സഹായം തിരഞ്ഞെടുക്കുക', title: 'നിങ്ങൾ ഏത് തരത്തിലുള്ള\nസഹായമാണ് തേടുന്നത്?', body: 'വ്യക്തമായ വഴി ആവശ്യമുള്ള ജീവിത മേഖലയിലൂടെ തുടങ്ങൂ. അടുത്ത ചോദ്യങ്ങൾ നിങ്ങളുടെ തിരഞ്ഞെടുപ്പിനനുസരിച്ച് മാറും.', search: 'വിഭാഗം തിരയുക', searchHint: '“വിദ്യാഭ്യാസം”, “കർഷകൻ” അല്ലെങ്കിൽ “ആരോഗ്യം” പരീക്ഷിക്കുക', signal: 'തുടരാൻ ഒന്ന് തിരഞ്ഞെടുക്കുക', foot: 'ഒൻപത് വഴികൾ · ഒരു വ്യക്തമായ അടുത്ത ഘട്ടം' },
  Bengali: { back: 'স্কিম সেতু', eyebrow: 'ধাপ 01 / সহায়তা বেছে নিন', title: 'আপনি কোন ধরনের\nসহায়তা খুঁজছেন?', body: 'জীবনের যে অংশে আপনার একটি পরিষ্কার পথ দরকার সেখান থেকে শুরু করুন। পরের প্রশ্নগুলি আপনার পছন্দ অনুযায়ী বদলাবে।', search: 'বিভাগ খুঁজুন', searchHint: '“শিক্ষা”, “কৃষক” বা “স্বাস্থ্য” চেষ্টা করুন', signal: 'এগোতে একটি বেছে নিন', foot: 'নয়টি পথ · একটি পরিষ্কার পরবর্তী ধাপ' },
}

export default function CategoryPage({ language = 'English', onBack, onSelect }) {
  const [query, setQuery] = useState('')
  const [active, setActive] = useState(null)
  const t = labels[getLanguage(language).name] || labels.English
  const filtered = useMemo(() => categoryData.filter((item) => `${item.title} ${item.sub} ${item.description}`.toLowerCase().includes(query.toLowerCase().trim())), [query])
  const choose = (item) => { setActive(item.id); window.setTimeout(() => onSelect?.(item.id), 160) }
  return <main className="category-page"><div className="category-topography" aria-hidden="true" /><header className="category-nav"><button type="button" className="category-back" onClick={onBack}><span aria-hidden="true">←</span><b>{t.back}</b></button><span className="category-progress"><i />01 / 04</span><span className="category-status">CIVIC ROUTER <b>ONLINE</b></span></header><div className="category-layout"><aside className="category-sidebar"><span className="sidebar-line" /><span className="sidebar-label">SCHEMESETU / CATEGORY ROUTER</span><span className="sidebar-step">01</span><span className="sidebar-step muted">02</span><span className="sidebar-step muted">03</span><span className="sidebar-step muted">04</span></aside><section className="category-main"><div className="category-intro"><p className="eyebrow"><span className="signal-dot" />{t.eyebrow}</p><h1>{t.title.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h1><p>{t.body}</p><label className="curved-input"><span aria-hidden="true">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.searchHint} aria-label={t.search} /><kbd>⌘ K</kbd></label></div><div className="category-signal"><span>{t.signal}</span><span>{filtered.length.toString().padStart(2, '0')} / 09 available</span></div><div className="category-stack" aria-live="polite">{filtered.map((item, index) => <button type="button" key={item.id} className={`category-route-card tone-${item.tone} ${active === item.id ? 'is-active' : ''}`} onClick={() => choose(item)}><span className="route-index">0{index + 1}</span><span className="route-code">{item.code}</span><span className="route-copy"><strong>{item.title}</strong><small>{item.sub}</small><p>{item.description}</p></span><span className="route-facts"><b>{item.current}</b><span>{item.national}</span></span><span className="route-arrow" aria-hidden="true">↗</span></button>)}</div><p className="category-footnote">{t.foot} <span>·</span> Official details are checked again before application.</p></section></div></main>
}
