import { useMemo, useState } from 'react'
import './DocumentChecklist.css'

function firstLink(value) { return String(value || '').match(/https?:\/\/[^\s)]+/i)?.[0] || '' }
export default function DocumentChecklist({ scheme, localizedDocuments, onBack, onFindAnother, onHome }) {
  const documents = useMemo(() => localizedDocuments?.length ? localizedDocuments : scheme?.documents || [], [localizedDocuments, scheme])
  const [checked, setChecked] = useState(() => new Set())
  const [copied, setCopied] = useState(false)
  if (!scheme) return null
  const toggle = (index) => setChecked((current) => { const next = new Set(current); if (next.has(index)) next.delete(index); else next.add(index); return next })
  const copy = async () => { const text = `${scheme.displayName || scheme.name}\n\n${documents.map((item, index) => `${checked.has(index) ? '[x]' : '[ ]'} ${item}`).join('\n')}`; try { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setCopied(false) } }
  const applyLink = firstLink(scheme.officialApplyLink) || firstLink(scheme.verificationSourceLink)
  const progress = documents.length ? Math.round((checked.size / documents.length) * 100) : 0
  return <main className="checklist-page checklist-page-rebuilt"><div className="checklist-lines" aria-hidden="true" /><header className="checklist-header"><button type="button" className="checklist-back" onClick={onBack}>← Back to scheme</button><span>DOCUMENT MODE / {scheme.category?.toUpperCase() || 'ROUTE'}</span></header><section className="checklist-rebuilt-layout"><div className="checklist-intro"><p className="eyebrow"><span className="signal-dot" />READY STATE / CHECKLIST</p><h1>Build your<br /><em>application stack.</em></h1><p>Use the record below as a preparation guide. Requirements can change by department, state, course, or applicant type.</p><div className="checklist-progress"><div><strong>{checked.size.toString().padStart(2, '0')}</strong><span>of {documents.length.toString().padStart(2, '0')} checked</span></div><div className="checklist-progress-bar"><span style={{ width: `${progress}%` }} /></div><small>{progress}% prepared</small></div></div><div className="checklist-card"><div className="checklist-card-top"><span>SCHEME DOSSIER</span><span>{scheme.displayName || scheme.name}</span></div><h2>Documents required</h2><p className="checklist-card-note">Mark what you already have. Items labelled as flags or “needs check” should be verified with the official department.</p><div className="checklist-items">{documents.length ? documents.map((item, index) => <button type="button" className={`checklist-item ${checked.has(index) ? 'is-checked' : ''}`} key={`${item}-${index}`} onClick={() => toggle(index)}><span className="checklist-box" aria-hidden="true">{checked.has(index) ? '✓' : ''}</span><span>{item}</span></button>) : <p className="checklist-missing">The dossier did not supply a document list. Check the official application portal before proceeding.</p>}</div><div className="checklist-actions"><button type="button" className="checklist-primary" onClick={copy}>{copied ? 'Checklist copied ✓' : 'Copy checklist ↗'}</button>{applyLink ? <a className="checklist-official" href={applyLink} target="_blank" rel="noreferrer">Open official portal ↗</a> : <span className="checklist-unavailable">Official portal link needs verification</span>}</div></div></section><footer className="checklist-footer"><button type="button" onClick={onFindAnother}>Find another scheme ↗</button><button type="button" onClick={onHome}>Return to SchemeSetu home</button></footer></main>
}
