import { useMemo, useState } from 'react'
import './DocumentChecklist.css'
import { getCopy, interpolate } from '../data/languages'

function firstLink(value) { return String(value || '').match(/https?:\/\/[^\s)]+/i)?.[0] || '' }
export default function DocumentChecklist({ scheme, localizedDocuments, language = 'English', onBack, onFindAnother, onHome }) {
  const copy = getCopy(language).checklist
  const documents = useMemo(() => localizedDocuments?.length ? localizedDocuments : scheme?.documents || [], [localizedDocuments, scheme])
  const [checked, setChecked] = useState(() => new Set())
  const [copied, setCopied] = useState(false)
  if (!scheme) return null
  const toggle = (index) => setChecked((current) => { const next = new Set(current); if (next.has(index)) next.delete(index); else next.add(index); return next })
  const copyChecklist = async () => { const text = `${scheme.displayName || scheme.name}\n\n${documents.map((item, index) => `${checked.has(index) ? '[x]' : '[ ]'} ${item}`).join('\n')}`; try { await navigator.clipboard.writeText(text); setCopied(true); window.setTimeout(() => setCopied(false), 1800) } catch { setCopied(false) } }
  const applyLink = firstLink(scheme.officialApplyLink) || firstLink(scheme.verificationSourceLink)
  const progress = documents.length ? Math.round((checked.size / documents.length) * 100) : 0
  return <main className="checklist-page checklist-page-rebuilt"><div className="checklist-lines" aria-hidden="true" /><header className="checklist-header"><button type="button" className="checklist-back" onClick={onBack}>← {copy.back}</button><span>{copy.step}</span></header><section className="checklist-rebuilt-layout"><div className="checklist-intro"><p className="eyebrow"><span className="signal-dot" />{copy.eyebrow}</p><h1>{copy.title}<br /><em>{copy.titleEm}</em></h1><p>{interpolate(copy.lede, { name: scheme.displayName || scheme.name })}</p><div className="checklist-progress"><div><strong>{checked.size.toString().padStart(2, '0')}</strong><span>{copy.checked}</span></div><div className="checklist-progress-bar"><span style={{ width: `${progress}%` }} /></div><small>{progress}% {copy.ready}</small></div></div><div className="checklist-card"><div className="checklist-card-top"><span>SCHEME DOSSIER</span><span>{scheme.displayName || scheme.name}</span></div><h2>{copy.aria}</h2><p className="checklist-card-note">{copy.lede}</p><div className="checklist-items">{documents.length ? documents.map((item, index) => <button type="button" className={`checklist-item ${checked.has(index) ? 'is-checked' : ''}`} key={`${item}-${index}`} onClick={() => toggle(index)}><span className="checklist-box" aria-hidden="true">{checked.has(index) ? '✓' : ''}</span><span>{item}</span></button>) : <p className="checklist-missing">{copy.missingDocument}</p>}</div><div className="checklist-actions"><button type="button" className="checklist-primary" onClick={copyChecklist}>{copied ? copy.copied : `${copy.copy} ↗`}</button>{applyLink ? <a className="checklist-official" href={applyLink} target="_blank" rel="noreferrer">{copy.backDetails} ↗</a> : <span className="checklist-unavailable">{copy.disclaimer}</span>}</div></div></section><footer className="checklist-footer"><button type="button" onClick={onFindAnother}>{copy.backDetails} ↗</button><button type="button" onClick={onHome}>{copy.back} · SchemeSetu</button></footer></main>
}
