import { useMemo, useState } from 'react'
import './InputScreen.css'
import { getLanguage } from '../data/languages'

const definitions = {
  education: { name: 'Education', eyebrow: 'EDUCATION SIGNAL / PROFILE', title: 'Tell us where you are in your learning path.', fact: 'The dossier includes 65 education records in this release.', fields: [{ key: 'education', label: 'Current study level', options: ['School', 'Undergraduate', 'Postgraduate', 'Technical diploma'] }, { key: 'category', label: 'Community or support category', options: ['General', 'OBC', 'SC', 'ST', 'Minority', 'Disability'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  health: { name: 'Health & wellness', eyebrow: 'HEALTH SIGNAL / PROFILE', title: 'Tell us what kind of care you need.', fact: 'Health routes include care, insurance, maternal support, and treatment programmes.', fields: [{ key: 'healthNeed', label: 'Primary need', options: ['Health insurance', 'Treatment support', 'Maternal care', 'Child health', 'Mental health', 'Telemedicine'] }, { key: 'ageGroup', label: 'Age group', options: ['Child', 'Young adult', 'Adult', 'Older adult'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L', 'No income limit'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  jobs: { name: 'Jobs & skills', eyebrow: 'WORKFORCE SIGNAL / PROFILE', title: 'Tell us where you want work to take you.', fact: 'Skill India’s three flagship components report more than 2.27 crore beneficiaries to date.', fields: [{ key: 'employmentStatus', label: 'Your current position', options: ['Looking for my first job', 'Unemployed', 'Working and upskilling', 'Self-employed', 'Student'] }, { key: 'ageGroup', label: 'Age group', options: ['15–24', '25–35', '36–45', '46+'] }, { key: 'education', label: 'Highest education or skill level', options: ['School', 'ITI / vocational', 'Diploma', 'Undergraduate', 'Postgraduate'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  housing: { name: 'Housing & utilities', eyebrow: 'LIVING SYSTEM / PROFILE', title: 'Tell us which part of home needs a clearer route.', fact: 'Housing and utility routes cover homes, water, sanitation, power, and clean fuel.', fields: [{ key: 'housingNeed', label: 'What do you need help with?', options: ['New home', 'Home repair', 'Water', 'Sanitation', 'Electricity', 'Cooking fuel'] }, { key: 'residence', label: 'Your residence', options: ['Rural', 'Urban', 'Peri-urban'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  finance: { name: 'Finance & insurance', eyebrow: 'FINANCIAL SIGNAL / PROFILE', title: 'Tell us what kind of financial cover you need.', fact: 'The combined dossier contains 50 finance and insurance records across two research parts.', fields: [{ key: 'financeNeed', label: 'Primary financial need', options: ['Bank account', 'Insurance', 'Pension', 'Credit or enterprise loan', 'Farmer credit', 'Savings'] }, { key: 'ageGroup', label: 'Age group', options: ['Under 18', '18–35', '36–59', '60+'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L', 'No income limit'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  agriculture: { name: 'Agriculture & livelihoods', eyebrow: 'FARM SIGNAL / PROFILE', title: 'Tell us what your farm or rural livelihood needs.', fact: 'Agriculture routes include farmer income, crop insurance, irrigation, livestock, fisheries, and rural enterprise.', fields: [{ key: 'farmerType', label: 'Your livelihood', options: ['Small or marginal farmer', 'Tenant farmer', 'Sharecropper', 'Livestock keeper', 'Fisher', 'Rural worker'] }, { key: 'cropNeed', label: 'What support do you need?', options: ['Income support', 'Crop insurance', 'Irrigation', 'Equipment', 'Livestock', 'Market or credit'] }, { key: 'landholding', label: 'Land or activity scale', options: ['Landless', 'Up to 2 hectares', '2–5 hectares', 'Above 5 hectares', 'Not applicable'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  women: { name: 'Women & child', eyebrow: 'CARE NETWORK / PROFILE', title: 'Tell us which care or opportunity route matters now.', fact: 'Women and child routes cover safety, nutrition, care, protection, and opportunity.', fields: [{ key: 'householdNeed', label: 'Primary need', options: ['Women’s safety', 'Maternal care', 'Child nutrition', 'Education', 'Livelihood', 'Child protection'] }, { key: 'ageGroup', label: 'Who needs support?', options: ['Girl child', 'Woman 18–35', 'Woman 36+', 'Pregnant woman', 'Child under 6', 'Family'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  social: { name: 'Social justice', eyebrow: 'DIGNITY SIGNAL / PROFILE', title: 'Tell us what kind of inclusion support you need.', fact: 'Social justice routes are designed around inclusion, welfare, dignity, and community support.', fields: [{ key: 'socialNeed', label: 'Primary need', options: ['Scholarship', 'Housing or livelihood', 'Rehabilitation', 'Protection', 'Community support', 'Legal or social assistance'] }, { key: 'category', label: 'Community or support category', options: ['SC', 'OBC', 'Minority', 'Senior citizen', 'Transgender person', 'Other eligible group'] }, { key: 'income', label: 'Annual family income', options: ['Below ₹1L', '₹1L–₹2.5L', '₹2.5L–₹5L', 'Above ₹5L'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
  disability: { name: 'Disability support', eyebrow: 'ACCESS SIGNAL / PROFILE', title: 'Tell us what access or inclusion support would help.', fact: 'Disability routes include scholarships, assistive devices, rehabilitation, and accessibility support.', fields: [{ key: 'supportNeed', label: 'Primary support need', options: ['Scholarship', 'Assistive device', 'Skill training', 'Rehabilitation', 'Accessibility', 'Care support'] }, { key: 'disabilityPercentage', label: 'Certified disability level', options: ['40–59%', '60–79%', '80%+', 'Not yet certified'] }, { key: 'ageGroup', label: 'Age group', options: ['Child', 'Student', 'Working age', 'Older adult'] }, { key: 'state', label: 'State or Union Territory', type: 'text' }] },
}

function SignalField() { return <div className="input-signal-field" aria-hidden="true"><span className="input-orbit input-orbit-one" /><span className="input-orbit input-orbit-two" /><span className="input-globe">INDIA</span><span className="input-scanline" /></div> }
function OptionField({ field, value, onChange }) { if (field.type === 'text') return <label className="input-text-field"><span>{field.label}</span><input value={value || ''} onChange={(event) => onChange(field.key, event.target.value)} placeholder="Type your answer" /></label>; return <fieldset className="input-choice-field"><legend>{field.label}</legend><div className="input-choice-grid">{field.options.map((option) => <button type="button" key={option} className={value === option ? 'is-selected' : ''} aria-pressed={value === option} onClick={() => onChange(field.key, option)}>{option}</button>)}</div></fieldset> }

export default function InputScreen({ onSubmit, onBack, initialLanguage = 'English', selectedCategory = 'education' }) {
  const category = definitions[selectedCategory] || definitions.education
  const [answers, setAnswers] = useState({ language: initialLanguage, categoryId: selectedCategory })
  const [submitted, setSubmitted] = useState(false)
  const language = getLanguage(answers.language).name
  const update = (key, value) => setAnswers((current) => ({ ...current, [key]: value }))
  const ready = useMemo(() => category.fields.every((field) => answers[field.key]), [answers, category.fields])
  const submit = (event) => { event.preventDefault(); if (!ready) { setSubmitted(true); return } onSubmit({ ...answers, category: selectedCategory }) }
  return <main className="input-page input-page-category"><div className="input-black-hole" aria-hidden="true" /><SignalField /><header className="input-nav"><button className="back-link" type="button" onClick={onBack}><span aria-hidden="true">←</span> Choose another route</button><span className="step-count">STEP 02 / 04 · {category.name.toUpperCase()}</span><span className="input-language">{language}</span></header><section className="input-workspace"><div className="input-heading"><p className="eyebrow"><span className="signal-dot" />{category.eyebrow}</p><h1>{category.title}</h1><p className="input-fact">{category.fact}</p><p className="input-instruction">Your answers stay focused on this route. We use them to rank the most relevant records in the current catalogue.</p></div><form className="input-bento" onSubmit={submit}><div className="input-bento-label"><span>PROFILE / 02</span><strong>Build your signal</strong><small>Fields adapt to {category.name.toLowerCase()}.</small></div>{category.fields.map((field) => <OptionField key={field.key} field={field} value={answers[field.key]} onChange={update} />)}<label className="input-text-field input-notes"><span>Anything else we should know <small>(optional)</small></span><textarea value={answers.notes || ''} onChange={(event) => update('notes', event.target.value)} placeholder="Add a location, urgency, or situation detail." rows="3" /></label>{submitted && !ready && <p className="input-error" role="alert">Complete each route-specific field to continue.</p>}<div className="input-submit-row"><button className="input-submit" type="submit"><span>Find matching schemes</span><span aria-hidden="true">↗</span></button><span className="input-privacy">No sign-up required · Official links are shown for verification</span></div></form></section></main>
}
