// Style direction: Civic Observatory — dark civic editorialism, graphite layers, signal amber, useful motion only.
import { useEffect, useState } from 'react'
import { getCopy, getLanguage, languages } from '../data/languages'
import MoltenMetal from './MoltenMetal'
import './Landing.css'

const publicDatasets = [
  { label: 'DBT / CUMULATIVE', value: 5300417, suffix: ' Cr', decimals: 0, title: 'Total benefit transfers since 2019–20', source: 'DBT Bharat national dashboard', href: 'https://dbtbharat.gov.in/' },
  { label: 'DBT / FY 2026–27', value: 183033, suffix: ' Cr', decimals: 0, title: 'Funds transferred in the current financial year', source: 'DBT Bharat national dashboard', href: 'https://dbtbharat.gov.in/' },
  { label: 'DBT / ESTIMATED GAINS', value: 514201.92, suffix: ' Cr', decimals: 2, title: 'Estimated gains reported by the DBT Mission', source: 'DBT Bharat national dashboard', href: 'https://dbtbharat.gov.in/static-page-content/spagecont?id=18' },
  { label: 'PM-KISAN / APR–JUL 2026–27', value: 94465646, suffix: '', decimals: 0, title: 'Farmers benefited in the latest listed period', source: 'PM-KISAN official portal', href: 'https://pmkisan.gov.in/' },
  { label: 'PM-KISAN / SUPPORT', value: 6000, prefix: '₹', suffix: ' / year', decimals: 0, title: 'Annual income support for eligible farmer families', source: 'PM-KISAN official portal', href: 'https://pmkisan.gov.in/' },
  { label: 'MYSCHEME / INDEXED', value: 4770, suffix: '+', decimals: 0, title: 'Government schemes listed across India', source: 'myScheme national platform', href: 'https://www.myscheme.gov.in/' },
]

const categories = [
  ['Education', 'ED', 'amber', '43 local records', 'Scholarships, fellowships, fees, and learning support'],
  ['Health & wellness', 'HL', 'blue', 'Explore route', 'Care, treatment, insurance, and family wellness'],
  ['Jobs & skills', 'JS', 'teal', 'Explore route', 'Training, apprenticeships, placement, and work'],
  ['Housing & utilities', 'HU', 'violet', 'Explore route', 'Homes, water, sanitation, power, and clean fuel'],
  ['Finance & insurance', 'FI', 'amber', 'Explore route', 'Accounts, credit, pensions, insurance, and income'],
  ['Agriculture & livelihoods', 'AL', 'green', 'Explore route', 'Farms, crop support, rural work, and enterprise'],
  ['Women & child', 'WC', 'rose', 'Explore route', 'Safety, nutrition, care, and opportunity'],
  ['Social justice', 'SJ', 'orange', 'Explore route', 'Inclusion, welfare, dignity, and community support'],
  ['Disability support', 'DS', 'cyan', 'Explore route', 'Access, aids, rehabilitation, and inclusion'],
]

const frontCopy = {
  English: { eyebrow: 'A clearer civic signal', title: 'Start with what you need.\nWe’ll narrow the path.', body: 'Find the public support that fits your situation.', start: 'Find my schemes', how: 'See how it works', need: 'Choose your starting point', needBody: 'Select the kind of support you need. Your next questions will adapt to it.', scale: 'The scale of support', scaleTitle: 'India’s support\nhas a signal.', scaleBody: 'Public programmes already move at national scale. Scheme Setu helps you find the part of that system that fits your life.', index: 'government schemes listed across India', dbt: 'schemes delivered through Direct Benefit Transfer', ministries: 'ministries represented', transactions: 'direct-benefit transactions reported in FY 2026–27', source: 'Official government dashboards · Checked 29 August 2026', disclaimer: 'Always confirm current details on the official government portal before applying.' },
  Hindi: { eyebrow: 'सहायता तक साफ़ रास्ता', title: 'अपनी ज़रूरत से शुरू करें।\nहम रास्ता आसान करेंगे।', body: 'बताइए कि आप किस तरह की सहायता ढूँढ रहे हैं। स्कीम सेतु आपकी स्थिति के अनुसार सरकारी योजनाएँ दिखाता है और अगला कदम समझाता है।', start: 'मेरी योजनाएँ खोजें', how: 'यह कैसे काम करता है', need: 'शुरुआत चुनें', needBody: 'आपको किस तरह की सहायता चाहिए, वह चुनें। अगले सवाल उसी के अनुसार बदलेंगे।', scale: 'सहायता का विस्तार', scaleTitle: 'भारत की सहायता\nआप तक पहुँचे।', scaleBody: 'सरकारी कार्यक्रम बड़े स्तर पर काम करते हैं। स्कीम सेतु आपको अपनी ज़रूरत के अनुसार सही रास्ता ढूँढने में मदद करता है।', index: 'पूरे भारत में सूचीबद्ध सरकारी योजनाएँ', dbt: 'प्रत्यक्ष लाभ अंतरण से दी जाने वाली योजनाएँ', ministries: 'मंत्रालय शामिल', transactions: 'वित्त वर्ष 2026–27 में दर्ज प्रत्यक्ष लाभ लेन-देन', source: 'आधिकारिक सरकारी डैशबोर्ड · जाँच 29 अगस्त 2026', disclaimer: 'आवेदन से पहले आधिकारिक सरकारी पोर्टल पर वर्तमान जानकारी की पुष्टि करें।' },
  Marathi: { eyebrow: 'मदतीचा स्पष्ट मार्ग', title: 'तुमच्या गरजेपासून सुरुवात करा.\nआम्ही मार्ग सोपा करू.', body: 'तुम्हाला कोणत्या प्रकारची मदत हवी आहे ते सांगा. योजना सेतू तुमच्या परिस्थितीशी संबंधित सरकारी योजना दाखवते आणि पुढील पाऊल समजावते.', start: 'माझ्या योजना शोधा', how: 'हे कसे कार्य करते', need: 'सुरुवातीची गरज निवडा', needBody: 'तुम्हाला कोणत्या प्रकारची मदत हवी आहे ते निवडा. पुढील प्रश्न त्यानुसार बदलतील.', scale: 'मदतीची व्याप्ती', scaleTitle: 'भारताची मदत\nतुमच्यापर्यंत.', scaleBody: 'सरकारी कार्यक्रम मोठ्या प्रमाणावर कार्यरत आहेत. योजना सेतू तुमच्या जीवनाला योग्य असलेला मार्ग शोधण्यात मदत करते.', index: 'भारतात सूचीबद्ध सरकारी योजना', dbt: 'थेट लाभ हस्तांतरणाद्वारे दिल्या जाणाऱ्या योजना', ministries: 'मंत्रालयांचा समावेश', transactions: 'आर्थिक वर्ष 2026–27 मधील थेट लाभ व्यवहार', source: 'अधिकृत सरकारी डॅशबोर्ड · तपासले 29 ऑगस्ट 2026', disclaimer: 'अर्ज करण्यापूर्वी अधिकृत सरकारी पोर्टलवर सध्याची माहिती तपासा.' },
  Tamil: { eyebrow: 'ஆதரவுக்கான தெளிவான பாதை', title: 'உங்கள் தேவையிலிருந்து தொடங்குங்கள்.\nபாதையை நாங்கள் எளிதாக்குவோம்.', body: 'எந்த வகையான ஆதரவைத் தேடுகிறீர்கள் என்று சொல்லுங்கள். ஸ்கீம் சேது உங்கள் சூழ்நிலைக்கு பொருத்தமான அரசு திட்டங்களை காட்டி அடுத்த படியை விளக்குகிறது.', start: 'எனக்கான திட்டங்களைத் தேடு', how: 'இது எப்படி செயல்படுகிறது', need: 'தொடக்கத் தேவையைத் தேர்ந்தெடுக்கவும்', needBody: 'உங்களுக்கு தேவையான ஆதரவைத் தேர்ந்தெடுக்கவும். அடுத்த கேள்விகள் அதற்கேற்ப மாறும்.', scale: 'ஆதரவின் அளவு', scaleTitle: 'இந்தியாவின் ஆதரவு\nஉங்களை அடையட்டும்.', scaleBody: 'அரசுத் திட்டங்கள் மிகப்பெரிய அளவில் செயல்படுகின்றன. உங்கள் வாழ்க்கைக்கு பொருந்தும் வழியை ஸ்கீம் சேது கண்டறிய உதவுகிறது.', index: 'இந்தியா முழுவதும் பட்டியலிடப்பட்ட அரசு திட்டங்கள்', dbt: 'நேரடி நலன் பரிமாற்றம் மூலம் வழங்கப்படும் திட்டங்கள்', ministries: 'அமைச்சகங்கள்', transactions: '2026–27 நிதியாண்டில் பதிவான நேரடி நலன் பரிமாற்றங்கள்', source: 'அதிகாரப்பூர்வ அரசு டாஷ்போர்டுகள் · 29 ஆகஸ்ட் 2026 அன்று சரிபார்க்கப்பட்டது', disclaimer: 'விண்ணப்பிக்கும் முன் அதிகாரப்பூர்வ அரசு தளத்தில் தற்போதைய தகவலை உறுதிப்படுத்தவும்.' },
  Kannada: { eyebrow: 'ಬೆಂಬಲಕ್ಕೆ ಸ್ಪಷ್ಟ ದಾರಿ', title: 'ನಿಮ್ಮ ಅಗತ್ಯದಿಂದ ಪ್ರಾರಂಭಿಸಿ.\nನಾವು ದಾರಿಯನ್ನು ಸರಳಗೊಳಿಸುತ್ತೇವೆ.', body: 'ನಿಮಗೆ ಯಾವ ರೀತಿಯ ಬೆಂಬಲ ಬೇಕು ಎಂದು ತಿಳಿಸಿ. ಸ್ಕೀಮ್ ಸೇತು ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಗೆ ಹೊಂದುವ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ತೋರಿಸಿ ಮುಂದಿನ ಹೆಜ್ಜೆಯನ್ನು ವಿವರಿಸುತ್ತದೆ.', start: 'ನನ್ನ ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ', how: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ', need: 'ಆರಂಭದ ಅಗತ್ಯವನ್ನು ಆರಿಸಿ', needBody: 'ನಿಮಗೆ ಬೇಕಾದ ಬೆಂಬಲವನ್ನು ಆರಿಸಿ. ಮುಂದಿನ ಪ್ರಶ್ನೆಗಳು ಅದಕ್ಕೆ ತಕ್ಕಂತೆ ಬದಲಾಗುತ್ತವೆ.', scale: 'ಬೆಂಬಲದ ವ್ಯಾಪ್ತಿ', scaleTitle: 'ಭಾರತದ ಬೆಂಬಲ\nನಿಮ್ಮವರೆಗೆ.', scaleBody: 'ಸರ್ಕಾರಿ ಕಾರ್ಯಕ್ರಮಗಳು ದೊಡ್ಡ ಪ್ರಮಾಣದಲ್ಲಿ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತಿವೆ. ನಿಮ್ಮ ಜೀವನಕ್ಕೆ ಹೊಂದುವ ದಾರಿಯನ್ನು ಹುಡುಕಲು ಸ್ಕೀಮ್ ಸೇತು ಸಹಾಯ ಮಾಡುತ್ತದೆ.', index: 'ಭಾರತದಾದ್ಯಂತ ಪಟ್ಟಿ ಮಾಡಲಾದ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು', dbt: 'ನೇರ ಲಾಭ ವರ್ಗಾವಣೆಯ ಮೂಲಕ ನೀಡಲಾಗುವ ಯೋಜನೆಗಳು', ministries: 'ಸಚಿವಾಲಯಗಳು', transactions: '2026–27 ಹಣಕಾಸು ವರ್ಷದಲ್ಲಿ ವರದಿಯಾದ ನೇರ ಲಾಭ ವ್ಯವಹಾರಗಳು', source: 'ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗಳು · 29 ಆಗಸ್ಟ್ 2026 ರಂದು ಪರಿಶೀಲಿಸಲಾಗಿದೆ', disclaimer: 'ಅರ್ಜಿ ಸಲ್ಲಿಸುವ ಮೊದಲು ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್‌ನಲ್ಲಿ ಪ್ರಸ್ತುತ ವಿವರಗಳನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.' },
  Malayalam: { eyebrow: 'സഹായത്തിലേക്കുള്ള വ്യക്തമായ വഴി', title: 'നിങ്ങളുടെ ആവശ്യത്തിൽ നിന്ന് തുടങ്ങൂ.\nവഴി ഞങ്ങൾ ലളിതമാക്കാം.', body: 'നിങ്ങൾ തേടുന്ന സഹായത്തിന്റെ തരം പറയൂ. സ്കീം സേതു നിങ്ങളുടെ സാഹചര്യത്തിന് അനുയോജ്യമായ സർക്കാർ പദ്ധതികൾ കാണിക്കുകയും അടുത്ത ഘട്ടം വിശദീകരിക്കുകയും ചെയ്യും.', start: 'എനിക്കുള്ള പദ്ധതികൾ കണ്ടെത്തുക', how: 'ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു', need: 'ആരംഭിക്കേണ്ട ആവശ്യം തിരഞ്ഞെടുക്കുക', needBody: 'നിങ്ങൾക്ക് ആവശ്യമായ സഹായം തിരഞ്ഞെടുക്കൂ. അടുത്ത ചോദ്യങ്ങൾ അതിനനുസരിച്ച് മാറും.', scale: 'സഹായത്തിന്റെ വ്യാപ്തി', scaleTitle: 'ഇന്ത്യയുടെ സഹായം\nനിങ്ങളിലേക്ക്.', scaleBody: 'സർക്കാർ പരിപാടികൾ വലിയ തോതിൽ പ്രവർത്തിക്കുന്നു. നിങ്ങളുടെ ജീവിതത്തിന് അനുയോജ്യമായ വഴി കണ്ടെത്താൻ സ്കീം സേതു സഹായിക്കുന്നു.', index: 'ഇന്ത്യയിലുടനീളം പട്ടികപ്പെടുത്തിയ സർക്കാർ പദ്ധതികൾ', dbt: 'നേരിട്ടുള്ള ആനുകൂല്യ കൈമാറ്റത്തിലൂടെ നൽകുന്ന പദ്ധതികൾ', ministries: 'മന്ത്രാലയങ്ങൾ ഉൾപ്പെടുന്നു', transactions: '2026–27 സാമ്പത്തിക വർഷത്തിലെ നേരിട്ടുള്ള ആനുകൂല്യ ഇടപാടുകൾ', source: 'ഔദ്യോഗിക സർക്കാർ ഡാഷ്ബോർഡുകൾ · 29 ഓഗസ്റ്റ് 2026 പരിശോധിച്ചു', disclaimer: 'അപേക്ഷിക്കുന്നതിന് മുമ്പ് ഔദ്യോഗിക സർക്കാർ പോർട്ടലിലെ നിലവിലെ വിവരങ്ങൾ സ്ഥിരീകരിക്കുക.' },
  Bengali: { eyebrow: 'সহায়তার একটি পরিষ্কার পথ', title: 'আপনার প্রয়োজন দিয়ে শুরু করুন।\nপথটি আমরা সহজ করব।', body: 'আপনি কী ধরনের সহায়তা খুঁজছেন তা বলুন। স্কিম সেতু আপনার পরিস্থিতির সঙ্গে মেলে এমন সরকারি প্রকল্প দেখায় এবং পরবর্তী ধাপটি বোঝায়।', start: 'আমার প্রকল্প খুঁজুন', how: 'এটি কীভাবে কাজ করে', need: 'শুরুর প্রয়োজন বেছে নিন', needBody: 'আপনার প্রয়োজনীয় সহায়তা বেছে নিন। পরের প্রশ্নগুলি সেই অনুযায়ী বদলাবে।', scale: 'সহায়তার বিস্তার', scaleTitle: 'ভারতের সহায়তা\nআপনার কাছে।', scaleBody: 'সরকারি কর্মসূচিগুলি বড় পরিসরে কাজ করে। আপনার জীবনের সঙ্গে মানানসই পথ খুঁজে পেতে স্কিম সেতু সাহায্য করে।', index: 'সারা ভারতে তালিকাভুক্ত সরকারি প্রকল্প', dbt: 'সরাসরি সুবিধা হস্তান্তরের মাধ্যমে দেওয়া প্রকল্প', ministries: 'মন্ত্রক অন্তর্ভুক্ত', transactions: '2026–27 অর্থবর্ষে রিপোর্ট করা সরাসরি সুবিধা লেনদেন', source: 'সরকারি ড্যাশবোর্ড · 29 আগস্ট 2026-এ যাচাই করা হয়েছে', disclaimer: 'আবেদন করার আগে সরকারি পোর্টালে বর্তমান তথ্য নিশ্চিত করুন।' },
}

function Mark() { return <span className="brand-mark" aria-hidden="true"><span /></span> }
function AnimatedMetric({ value, prefix = '', suffix = '', decimals = 0 }) { const [display, setDisplay] = useState(0); useEffect(() => { let frame; const started = performance.now(); const duration = 1050; const tick = (now) => { const progress = Math.min(1, (now - started) / duration); const eased = 1 - Math.pow(1 - progress, 3); setDisplay(value * eased); if (progress < 1) frame = requestAnimationFrame(tick) }; frame = requestAnimationFrame(tick); return () => cancelAnimationFrame(frame) }, [value]); return <>{prefix}{display.toLocaleString('en-IN', { maximumFractionDigits: decimals, minimumFractionDigits: decimals })}{suffix}</> }
function LanguageMenu({ language, onLanguageChange }) { const [open, setOpen] = useState(false); const current = getLanguage(language); return <div className="language-menu"><button className="language-trigger" type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open}><span aria-hidden="true">◎</span><span>{current.name === 'English' ? 'EN' : current.name.slice(0, 2).toUpperCase()}</span><span aria-hidden="true">⌄</span></button>{open && <div className="language-popover">{languages.map((item) => <button type="button" key={item.name} className={`language-option ${current.name === item.name ? 'selected' : ''}`} onClick={() => { onLanguageChange?.(item.name); setOpen(false) }}><span>{item.nativeName}</span><small>{item.name}</small>{current.name === item.name && <span aria-hidden="true">✓</span>}</button>)}</div>}</div> }
function MaskedHeading({ children }) { return <span className="masked-heading">{children.split('\n').map((line, index) => <span className="heading-line" key={line} style={{ animationDelay: `${index * 90}ms` }}>{line}</span>)}</span> }
function CategoryCard({ category, index, onStart }) { return <button type="button" className={`category-card category-${category[2]}`} onClick={onStart}><span className="category-icon">{category[1]}</span><span className="category-body"><small>0{index + 1} / SECTOR</small><strong>{category[0]}</strong><em>{category[4]}</em></span><span className="category-meta"><b>{category[3]}</b><span aria-hidden="true">↗</span></span></button> }

export default function Landing({ onStart, language = 'English', onLanguageChange, accountPanel, onBrowse, onLatest }) {
  const copy = getCopy(language).landing
  const t = frontCopy[getLanguage(language).name] || frontCopy.English
  const [mobileOpen, setMobileOpen] = useState(false)
  const start = () => { setMobileOpen(false); onStart?.() }
  const nav = <><a href="#discover" onClick={() => setMobileOpen(false)}>{copy.nav?.howItWorks || t.how}</a><button type="button" onClick={() => { setMobileOpen(false); onBrowse?.() }}>{copy.nav?.schemes || 'Explore schemes'}</button><button type="button" onClick={() => { setMobileOpen(false); onLatest?.() }}>{copy.latest || 'Latest updates'}</button></>
  return <div className="landing-page" id="top"><header className="site-nav"><a href="#top" className="wordmark" aria-label="SchemeSetu home"><Mark /><span>Scheme<span className="wordmark-accent">Setu</span></span></a><nav className="desktop-nav" aria-label="Primary navigation">{nav}</nav><div className="topbar-actions"><LanguageMenu language={language} onLanguageChange={onLanguageChange} />{accountPanel}<button type="button" className="mobile-menu" aria-label={mobileOpen ? 'Close navigation' : 'Open navigation'} onClick={() => setMobileOpen((value) => !value)}>{mobileOpen ? <span aria-hidden="true">×</span> : <span aria-hidden="true">≡</span>}</button></div>{mobileOpen && <nav className="mobile-nav" aria-label="Mobile navigation">{nav}</nav>}</header><main>
    <section className="hero-section" id="discover"><div className="hero-atmosphere" aria-hidden="true"><MoltenMetal color1="#070B12" color2="#5B6672" color3="#D8E0E7" speed={0.12} scale={5.4} detail={4} glow={1.65} coreSize={0.2} swirl={1.4} fold={-0.36} blackPoint={0.02} brightness={1.3} colorMode="frost" grain grainIntensity={0.06} mouseInteraction mouseStrength={0.32} opacity={0.82} /><div className="particle-constellation">{Array.from({ length: 36 }, (_, index) => <i key={index} style={{ '--i': index }} />)}</div><div className="hero-contour contour-a" /><div className="hero-contour contour-b" /></div><div className="hero-orb" aria-hidden="true"><span className="orb-core" /><span className="orb-ring orb-ring-a" /><span className="orb-ring orb-ring-b" /><span className="orb-ray orb-ray-a" /><span className="orb-ray orb-ray-b" />{Array.from({ length: 24 }, (_, index) => <i key={index} style={{ '--orb-i': index }} />)}</div><div className="hero-copy"><div className="eyebrow"><span className="signal-dot" />{t.eyebrow}<span className="eyebrow-rule" /></div><h1><MaskedHeading>{t.title}</MaskedHeading></h1><p className="hero-body">{t.body}</p><div className="hero-actions"><button type="button" className="primary-button" onClick={start}>{t.start} <span aria-hidden="true">↗</span></button><a className="quiet-link" href="#how-it-works">{t.how} <span>↘</span></a></div><p className="hero-disclaimer">No sign-up required.</p><div className="hero-trustbar" aria-label="SchemeSetu support routes">{categories.map(([name, code]) => <span key={code}>{name}</span>)}</div></div></section>
    <section className="category-section section-frame" id="coverage"><div className="section-header"><div><p className="eyebrow"><span className="signal-dot" />{t.need}</p><h2>{t.need}</h2></div><p className="section-note">{t.needBody}</p></div><div className="category-grid">{categories.map((category, index) => <CategoryCard key={category[0]} category={category} index={index} onStart={start} />)}</div></section>
    <section className="civic-stats-section section-frame" aria-labelledby="civic-stats-title"><div className="stats-heading"><p className="eyebrow"><span className="signal-dot" />{t.scale}</p><h2 id="civic-stats-title">{t.scaleTitle.split('\n').map((line) => <span key={line}>{line}<br /></span>)}</h2><p>{t.scaleBody}</p></div><div><div className="civic-stats-grid"><a className="civic-stat-card stat-featured stat-scale-hero" href="https://www.myscheme.gov.in/" target="_blank" rel="noreferrer"><span className="stat-card-label">MYSCHEME / INDEXED</span><strong>4,770<small>+</small></strong><span>{t.index}</span><b>Open official index ↗</b></a><a className="civic-stat-card stat-scale-network" href="https://dbtbharat.gov.in/central-scheme/list" target="_blank" rel="noreferrer"><span className="stat-card-label">DBT / CENTRAL NETWORK</span><strong>320</strong><span>{t.dbt}</span><b>56 {t.ministries}</b></a><a className="civic-stat-card stat-live-activity" href="https://dbtbharat.gov.in/" target="_blank" rel="noreferrer"><span className="stat-card-label">DBT / FY 2026–27</span><strong>219<small> Cr</small></strong><span>{t.transactions}</span><b>Government dashboard ↗</b></a></div><p className="stats-source-note">{t.source}</p></div></section>
    <section className="public-data-section section-frame" aria-labelledby="public-data-title"><div className="public-data-heading"><p className="eyebrow"><span className="signal-dot" />LIVE PUBLIC RECORD</p><h2 id="public-data-title">The system is<br /><em>already moving.</em></h2><p>These figures come from national government dashboards. Scheme Setu turns a large public system into a clearer personal route.</p></div><div className="public-data-groups"><section className="public-data-cluster" aria-labelledby="dbt-cluster-title"><div className="public-data-cluster-head"><span>01 / DBT NETWORK</span><strong id="dbt-cluster-title">Scale of the system</strong><small>National transfer infrastructure</small></div><div className="public-data-grid">{publicDatasets.slice(0, 3).map((dataset) => <a className={`public-data-card public-data-${dataset.label.startsWith('DBT') ? 'dbt' : dataset.label.startsWith('PM-KISAN') ? 'pm-kisan' : 'index'}${dataset.label === 'DBT / CUMULATIVE' ? ' public-data-hero' : ''}`} href={dataset.href} target="_blank" rel="noreferrer" key={dataset.label}><span className="stat-card-label">{dataset.label}</span><strong><AnimatedMetric value={dataset.value} prefix={dataset.prefix} suffix={dataset.suffix} decimals={dataset.decimals} /></strong><span>{dataset.title}</span><small>{dataset.source} ↗</small></a>)}</div></section><section className="public-data-cluster public-data-cluster-secondary" aria-labelledby="reach-cluster-title"><div className="public-data-cluster-head"><span>02 / REACH & ACCESS</span><strong id="reach-cluster-title">Where support lands</strong><small>Household and discovery signals</small></div><div className="public-data-grid">{publicDatasets.slice(3).map((dataset) => <a className={`public-data-card public-data-${dataset.label.startsWith('DBT') ? 'dbt' : dataset.label.startsWith('PM-KISAN') ? 'pm-kisan' : 'index'}${dataset.label === 'DBT / CUMULATIVE' ? ' public-data-hero' : ''}`} href={dataset.href} target="_blank" rel="noreferrer" key={dataset.label}><span className="stat-card-label">{dataset.label}</span><strong><AnimatedMetric value={dataset.value} prefix={dataset.prefix} suffix={dataset.suffix} decimals={dataset.decimals} /></strong><span>{dataset.title}</span><small>{dataset.source} ↗</small></a>)}</div></section></div></section>
    <section className="stats-section section-frame"><div className="stats-intro"><p className="eyebrow">{copy.why}</p><h2>{copy.lessSearching}<br /><em>{copy.moreCertainty}</em></h2><p>{copy.whyBody}</p><a className="text-link" href="#how-it-works">{copy.simpleFlow} <span aria-hidden="true">↗</span></a></div><div className="stats-panel"><div className="stat-row"><span className="stat-number">01</span><div><strong>One focused start</strong><p>Begin with the kind of help you need, not a scheme name you may not know.</p></div><span className="stat-symbol">↗</span></div><div className="stat-row"><span className="stat-number">02</span><div><strong>Relevant by design</strong><p>Category-specific questions keep matches close to your actual situation.</p></div><span className="stat-symbol">◎</span></div><div className="stat-row"><span className="stat-number">03</span><div><strong>Ready for the next step</strong><p>Understand the fit, prepare your documents, and continue to the official source.</p></div><span className="stat-symbol">✓</span></div></div></section>
    <section className="how-section section-frame" id="how-it-works"><div className="how-heading"><p className="eyebrow">{copy.simpleFlow}</p><h2>{copy.flow?.[0]}<br /><em>{copy.flow?.[1]}</em></h2></div><div className="steps-list"><div className="step-item"><span>01</span><div><strong>{copy.flow?.[0]}</strong><p>{copy.flow?.[0]}</p></div><span>↗</span></div><div className="step-item"><span>02</span><div><strong>{copy.flow?.[1]}</strong><p>{copy.flow?.[1]}</p></div><span>↗</span></div><div className="step-item"><span>03</span><div><strong>{copy.flow?.[2]}</strong><p>{copy.flow?.[2]}</p></div><span>↗</span></div></div></section>
    </main><footer className="site-footer"><div className="footer-brand"><Mark /><span>Scheme<span className="wordmark-accent">Setu</span></span><small>PUBLIC SUPPORT, MADE CLEARER.</small></div><div className="footer-note"><span><i className="signal-dot" />{t.disclaimer}</span><span>© 2026 SchemeSetu</span></div></footer></div>
}
