import { useState } from 'react'
import './SchemeDetail.css'
import './VisualStack.css'
import { categoryRecordCounts } from '../data/fullSchemes'
import { getCopy, getDetailFallback, interpolate } from '../data/languages'
import { BorderGlow, ShapeGrid, Stepper } from './VisualStack'

function isRealLink(link) { return typeof link === 'string' && /^https?:\/\//i.test(link.trim()) }
function firstLink(value) { return String(value || '').match(/https?:\/\/[^\s)]+/i)?.[0] || '' }
function DetailPanel({ label, title, children, active = false }) { return <section className={`detail-panel ${active ? 'is-active' : ''}`}><p className="detail-panel-label">{label}</p><h2>{title}</h2><div className="detail-panel-body">{children}</div></section> }
function firstCurrency(value = '') { return value.match(/₹\s*[\d,]+(?:\.\d+)?(?:\s*\/\s*(?:month|year|annum))?/i)?.[0] || '' }
function isMissing(value) { return !value || /not stated|not specified|verify current|no url supplied|research date/i.test(value) }

const detailUi = {
  English: { back: 'Back to matches', step: 'STEP 03 / SCHEME DETAIL', verified: 'VERIFIED RECORD', read: 'READ THE DOSSIER', checks: 'Move through the route in four checks.', labels: ['01 / WHY THIS ROUTE', '02 / WHAT IT OPENS', '03 / SOURCE TRACE', '04 / RESEARCH NOTE'], dashboard: 'RECORD DASHBOARD', values: 'DATASET VALUES ONLY · NO ESTIMATES', ministry: 'Government of India', age: 'Age signal', income: 'Income signal', cost: 'Cost or contribution', window: 'Application window', source: 'View source reference', footer: 'SchemeSetu helps you find the route. The official department decides eligibility and approval.' },
  Hindi: { back: 'मिलान पर वापस जाएँ', step: 'चरण 03 / योजना विवरण', verified: 'सत्यापित रिकॉर्ड', read: 'विवरण पढ़ें', checks: 'चार चरणों में योजना देखें।', labels: ['01 / यह आपके लिए क्यों', '02 / क्या लाभ मिलेगा', '03 / स्रोत की जाँच', '04 / शोध नोट'], dashboard: 'रिकॉर्ड डैशबोर्ड', values: 'केवल डेटासेट मान · अनुमान नहीं', ministry: 'भारत सरकार', age: 'आयु संकेत', income: 'आय संकेत', cost: 'लागत या योगदान', window: 'आवेदन अवधि', source: 'स्रोत देखें', footer: 'SchemeSetu आपको सही मार्ग खोजने में मदद करता है। पात्रता और स्वीकृति का निर्णय आधिकारिक विभाग करता है।' },
  Marathi: { back: 'मॅचवर परत जा', step: 'चरण 03 / योजना तपशील', verified: 'तपासलेली नोंद', read: 'तपशील वाचा', checks: 'चार तपासण्यांमध्ये मार्ग पहा.', labels: ['01 / हा मार्ग का', '02 / काय मिळेल', '03 / स्रोत तपासा', '04 / संशोधन नोंद'], dashboard: 'नोंद डॅशबोर्ड', values: 'फक्त डेटासेट मूल्ये · अंदाज नाही', ministry: 'भारत सरकार', age: 'वयाचा संकेत', income: 'उत्पन्नाचा संकेत', cost: 'खर्च किंवा योगदान', window: 'अर्जाचा कालावधी', source: 'स्रोत पहा', footer: 'SchemeSetu तुम्हाला मार्ग शोधण्यात मदत करते. पात्रता आणि मंजुरीचा निर्णय अधिकृत विभाग घेतो.' },
  Tamil: { back: 'பொருத்தங்களுக்கு திரும்பு', step: 'படி 03 / திட்ட விவரம்', verified: 'சரிபார்க்கப்பட்ட பதிவு', read: 'விவரத்தைப் படிக்கவும்', checks: 'நான்கு சரிபார்ப்புகளில் வழியைப் பாருங்கள்.', labels: ['01 / ஏன் இந்த வழி', '02 / என்ன கிடைக்கும்', '03 / ஆதாரத்தைச் சரிபார்க்கவும்', '04 / ஆய்வு குறிப்பு'], dashboard: 'பதிவு டாஷ்போர்டு', values: 'தரவுத்தொகுப்பு மதிப்புகள் மட்டும் · மதிப்பீடுகள் இல்லை', ministry: 'இந்திய அரசு', age: 'வயது குறிப்பு', income: 'வருமான குறிப்பு', cost: 'செலவு அல்லது பங்களிப்பு', window: 'விண்ணப்ப காலம்', source: 'ஆதாரத்தைப் பார்க்கவும்', footer: 'SchemeSetu உங்களுக்கு வழியைக் கண்டறிய உதவுகிறது. தகுதி மற்றும் ஒப்புதலை அதிகாரப்பூர்வ துறை தீர்மானிக்கும்.' },
  Kannada: { back: 'ಹೊಂದಾಣಿಕೆಗಳಿಗೆ ಹಿಂತಿರುಗಿ', step: 'ಹಂತ 03 / ಯೋಜನೆ ವಿವರ', verified: 'ಪರಿಶೀಲಿಸಿದ ದಾಖಲೆ', read: 'ವಿವರ ಓದಿ', checks: 'ನಾಲ್ಕು ಪರಿಶೀಲನೆಗಳಲ್ಲಿ ಮಾರ್ಗವನ್ನು ನೋಡಿ.', labels: ['01 / ಈ ಮಾರ್ಗ ಏಕೆ', '02 / ಏನು ಸಿಗುತ್ತದೆ', '03 / ಮೂಲ ಪರಿಶೀಲನೆ', '04 / ಸಂಶೋಧನಾ ಟಿಪ್ಪಣಿ'], dashboard: 'ದಾಖಲೆ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', values: 'ಡೇಟಾಸೆಟ್ ಮೌಲ್ಯಗಳು ಮಾತ್ರ · ಅಂದಾಜುಗಳಿಲ್ಲ', ministry: 'ಭಾರತ ಸರ್ಕಾರ', age: 'ವಯಸ್ಸಿನ ಸೂಚನೆ', income: 'ಆದಾಯದ ಸೂಚನೆ', cost: 'ವೆಚ್ಚ ಅಥವಾ ಕೊಡುಗೆ', window: 'ಅರ್ಜಿ ಅವಧಿ', source: 'ಮೂಲ ನೋಡಿ', footer: 'SchemeSetu ನಿಮಗೆ ಸರಿಯಾದ ದಾರಿಯನ್ನು ಕಂಡುಹಿಡಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಅರ್ಹತೆ ಮತ್ತು ಅನುಮೋದನೆಯನ್ನು ಅಧಿಕೃತ ಇಲಾಖೆ ನಿರ್ಧರಿಸುತ್ತದೆ.' },
  Malayalam: { back: 'മാച്ചുകളിലേക്ക് മടങ്ങുക', step: 'ഘട്ടം 03 / പദ്ധതി വിശദാംശം', verified: 'പരിശോധിച്ച രേഖ', read: 'വിശദാംശങ്ങൾ വായിക്കുക', checks: 'നാല് പരിശോധനകളിലൂടെ വഴി കാണുക.', labels: ['01 / ഈ വഴി എന്തുകൊണ്ട്', '02 / എന്ത് ലഭിക്കും', '03 / ഉറവിടം പരിശോധിക്കുക', '04 / ഗവേഷണ കുറിപ്പ്'], dashboard: 'രേഖാ ഡാഷ്ബോർഡ്', values: 'ഡാറ്റാസെറ്റ് മൂല്യങ്ങൾ മാത്രം · കണക്കുകൂട്ടലുകളില്ല', ministry: 'ഇന്ത്യാ സർക്കാർ', age: 'പ്രായ സൂചന', income: 'വരുമാന സൂചന', cost: 'ചെലവ് അല്ലെങ്കിൽ സംഭാവന', window: 'അപേക്ഷാ കാലയളവ്', source: 'ഉറവിടം കാണുക', footer: 'SchemeSetu വഴി കണ്ടെത്താൻ നിങ്ങളെ സഹായിക്കുന്നു. യോഗ്യതയും അംഗീകാരവും ഔദ്യോഗിക വകുപ്പ് തീരുമാനിക്കുന്നു.' },
  Bengali: { back: 'ম্যাচে ফিরে যান', step: 'ধাপ 03 / প্রকল্পের বিবরণ', verified: 'যাচাই করা রেকর্ড', read: 'বিবরণ পড়ুন', checks: 'চারটি ধাপে পথটি দেখুন।', labels: ['01 / কেন এই পথ', '02 / কী সুবিধা মিলবে', '03 / উৎস যাচাই', '04 / গবেষণা নোট'], dashboard: 'রেকর্ড ড্যাশবোর্ড', values: 'শুধু ডেটাসেটের মান · কোনো অনুমান নয়', ministry: 'ভারত সরকার', age: 'বয়সের সংকেত', income: 'আয়ের সংকেত', cost: 'খরচ বা অবদান', window: 'আবেদনের সময়কাল', source: 'উৎস দেখুন', footer: 'SchemeSetu আপনাকে পথ খুঁজে নিতে সাহায্য করে। যোগ্যতা ও অনুমোদনের সিদ্ধান্ত সরকারি বিভাগ নেয়।' },
  Telugu: { back: 'సరిపోలిన వాటికి తిరిగి వెళ్లండి', step: 'దశ 03 / పథకం వివరాలు', verified: 'ధృవీకరించిన రికార్డు', read: 'వివరాలు చదవండి', checks: 'నాలుగు పరిశీలనల్లో మార్గాన్ని చూడండి.', labels: ['01 / ఈ మార్గం ఎందుకు', '02 / ఏమి లభిస్తుంది', '03 / మూలాన్ని తనిఖీ చేయండి', '04 / పరిశోధన గమనిక'], dashboard: 'రికార్డు డ్యాష్‌బోర్డ్', values: 'డేటాసెట్ విలువలు మాత్రమే · అంచనాలు లేవు', ministry: 'భారత ప్రభుత్వం', age: 'వయస్సు సూచన', income: 'ఆదాయ సూచన', cost: 'ఖర్చు లేదా సహకారం', window: 'దరఖాస్తు కాలం', source: 'మూలాన్ని చూడండి', footer: 'SchemeSetu మార్గాన్ని కనుగొనడంలో మీకు సహాయపడుతుంది. అర్హత మరియు ఆమోదాన్ని అధికారిక శాఖ నిర్ణయిస్తుంది.' },
  Gujarati: { back: 'મેચ પર પાછા જાઓ', step: 'પગલું 03 / યોજના વિગતો', verified: 'ચકાસાયેલ રેકોર્ડ', read: 'વિગતો વાંચો', checks: 'ચાર તપાસમાં માર્ગ જુઓ.', labels: ['01 / આ માર્ગ શા માટે', '02 / શું મળશે', '03 / સ્રોત તપાસો', '04 / સંશોધન નોંધ'], dashboard: 'રેકોર્ડ ડેશબોર્ડ', values: 'ફક્ત ડેટાસેટ મૂલ્યો · કોઈ અંદાજ નહીં', ministry: 'ભારત સરકાર', age: 'ઉંમર સંકેત', income: 'આવક સંકેત', cost: 'ખર્ચ અથવા યોગદાન', window: 'અરજી સમયગાળો', source: 'સ્રોત જુઓ', footer: 'SchemeSetu તમને યોગ્ય માર્ગ શોધવામાં મદદ કરે છે. પાત્રતા અને મંજૂરીનો નિર્ણય અધિકૃત વિભાગ કરે છે.' },
}


export default function SchemeDetail({ scheme, language = 'English', aiDetail, aiStatus, onBack, onChecklist }) {
  const [activeStage, setActiveStage] = useState(1)
  const copy = getCopy(language).detail
  const ui = detailUi[language] || detailUi.English
  const fallback = getDetailFallback(language)
  if (!scheme) return null
  const displayName = aiDetail?.name || scheme.displayName || scheme.name
  const applyLink = firstLink(scheme.officialApplyLink) || firstLink(scheme.verificationSourceLink)
  const documents = aiDetail?.documents?.length ? aiDetail.documents : scheme.documents || []
  const routeRecords = categoryRecordCounts[scheme.category] || 0
  const recordedAmount = firstCurrency(scheme.benefits || '') || firstCurrency(scheme.premium || '')
  const target = !isMissing(scheme.targetBeneficiary) ? scheme.targetBeneficiary : copy.fallbackBefore
  const stages = [copy.why, copy.support, copy.checklist, copy.before]
  const stageTitles = [copy.why, copy.support, copy.checklist, copy.before]
  const stageLabel = ui.labels
  const stageContent = [
    <><p>{aiDetail?.why || scheme.plainEligibility || scheme.officialEligibility || fallback.why}</p>{scheme.ageEligibility && <p className="detail-note"><b>{ui.age}:</b> {scheme.ageEligibility}</p>}{scheme.incomeCeiling && <p className="detail-note"><b>{ui.income}:</b> {scheme.incomeCeiling}</p>}</>,
    <><p>{aiDetail?.support || fallback.support}</p>{scheme.premium && <p className="detail-note"><b>{ui.cost}:</b> {scheme.premium}</p>}</>,
    <><p>{aiDetail?.notesFlags || aiDetail?.beforeApply || fallback.before}</p><p className="detail-note"><b>{ui.window}:</b> {aiDetail?.applicationWindow || copy.before}</p><div className="detail-actions"><button className="detail-primary" type="button" onClick={onChecklist}>{copy.checklist} <span>↗</span></button>{isRealLink(applyLink) ? <a className="detail-secondary" href={applyLink} target="_blank" rel="noreferrer">{copy.official} ↗</a> : <span className="detail-unavailable">{copy.linkNote}</span>}</div></>,
    <><p>{aiDetail?.beforeApply || fallback.before}</p>{scheme.verificationSourceLink && <a className="detail-source-link" href={firstLink(scheme.verificationSourceLink) || undefined} target="_blank" rel="noreferrer">{ui.source} ↗</a>}</>,
  ]
  const dashboard = [{ value: recordedAmount || 'See benefits', label: 'recorded support' }, { value: target, label: 'target beneficiary' }, { value: routeRecords || '—', label: 'records in route' }, { value: documents.length || '—', label: 'document signals' }]

  return <main className="scheme-detail-page scheme-detail-rebuilt"><ShapeGrid /><header className="detail-header"><button className="detail-back-link" type="button" onClick={onBack}><span aria-hidden="true">←</span> {ui.back}</button><span className="detail-step">{ui.step}</span><span className="detail-live">{ui.verified}</span></header><section className="detail-rebuilt-hero"><div className="detail-rebuilt-title"><p className="eyebrow"><span className="signal-dot" />{scheme.category} / {scheme.sourceType === 'existing-verified' ? 'CORE DATASET' : 'MASTER DOSSIER'}</p><h1>{displayName}</h1><p className="detail-ministry">{aiDetail?.ministry || scheme.ministry || 'Government of India'}</p><p className="detail-verification">{interpolate(copy.verified, { date: scheme.lastVerifiedDate || '—' })}</p>{aiStatus && <p className="detail-ai-status" role="status">{aiStatus.message}</p>}</div><BorderGlow className="detail-dashboard-glow"><div className="detail-dashboard"><div className="detail-dashboard-head"><span>{ui.dashboard}</span><small>{ui.values}</small></div><div className="detail-stats-grid">{dashboard.map((stat) => <div key={stat.label}><strong>{stat.value}</strong><span>{stat.label}</span></div>)}</div></div></BorderGlow></section><section className="detail-rebuilt-content"><div className="detail-stage-nav"><div className="detail-stage-intro"><span>{ui.read}</span><strong>{ui.checks}</strong></div><Stepper steps={stages} current={activeStage} /></div><div className="detail-stage-tabs" role="tablist" aria-label="Scheme detail stages">{stages.map((stage, index) => <button type="button" key={stage} className={activeStage === index + 1 ? 'is-active' : ''} onClick={() => setActiveStage(index + 1)} role="tab" aria-selected={activeStage === index + 1}><span>{String(index + 1).padStart(2, '0')}</span>{stage}</button>)}</div><div className="detail-rebuilt-grid">{stageContent.map((content, index) => <DetailPanel key={stageTitles[index]} label={stageLabel[index]} title={stageTitles[index]} active={activeStage === index + 1}>{content}</DetailPanel>)}</div></section><footer className="detail-footer">{ui.footer}</footer></main>
}
